name: workflow con uses nodejs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v6
      
      - name: Listar archivos
        run: ls -la

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      
      - name: Verificar version de Node.js
        run: |
          node -v
          npm -v