name: Invocador Workflow output
on:
  push:
    branches:
      - master


jobs:
  example-builder:
    uses: ./.github/workflows/reusable-workflow.yml
  
  deploy:
    runs-on: ubuntu-latest
    needs: example-builder
    steps:
      - name: Mostrar versión de npm
        run: |
          echo "Versión de npm: ${{ needs.example-builder.outputs.version }}"