name: Inicial workflow

on:
  push:

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Simula test
        run: echo "Simulando test...."

      - name: Simula build
        run: echo "Simulando build...."

      - name: simular error
        run: exit 1