name: Hello World Github Actions

on:
  workflow_dispatch:

jobs:
  data-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Directorios
        run: |
          echo "Directorio de trabajo: $GITHUB_WORKSPACE"
          echo "Directorio actual: $(pwd)"
          ls -la

  build:
    needs: data-output
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          echo "Building project..."
          echo "Directorio de trabajo: $GITHUB_WORKSPACE"
          echo "Directorio actual: $(pwd)"
          ls -la
    
  deploy:
    runs-on: ubuntu-latest
    needs: [data-output, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy
        run: |
          echo "Deploying project..."
          echo "Directorio de trabajo: $GITHUB_WORKSPACE"
          echo "Directorio actual: $(pwd)"
          ls -la
  

  logging:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Logging
        run: |
          echo "Logging information..."
          echo "Directorio de trabajo: $GITHUB_WORKSPACE"
          echo "Directorio actual: $(pwd)"
          ls -la

