name: Workflow basico concurrency job

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: sleep 60
        run: sleep 120

      - name: Run tests
        run: echo Running tests...
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    concurrency:
      group: production-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        run: echo Deploying application...