name: workflow reutilizable con parametros

on:
  workflow_call:
    inputs:
      node-version:
        type: string # recibe el tipo de dato (string, number, boolean, etc.)
        description: 'Node.js version to use'
        required: true
        default: '16'


jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
    
      - name: Show node version
        run: node -v

      - name: show npm version
        run: npm -v
