name: workflow reutilizable con un output

on:
  workflow_call:
    outputs:
      version:
        description: "Versión de npm"
        value: ${{ jobs.builder.steps.node-version.outputs.version }}

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      # - id: node-version
      #   run: echo "::set-output name=version::$(node -v)"

      - name: node version
        run: node -v
      
      - id: node-version
        name: set output
        run: |
          echo "version=$(node -v)" >> "$GITHUB_OUTPUT"

      - name: Final message
        run: echo "Build simulation complete"