name: Segundo Workflow

on:
  workflow_run:
    workflows: ["Basico Workflow"]
    types:
      - requested

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Say segundo workflow
        run: echo "Hola mundo desde el segundo workflow, gatillado por el workflow Basico Workflow"