name: Inicial workflow

on:
  push:

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Simula test
        run: echo "Simulando test...."

      - name: Simula build
        run: echo "Simulando build...."

      - name: simulando paso 1
        run: echo "Simulando paso 1...."

      - name: simulando paso 2
        run: echo "Simulando paso 2...."

      - name: simulando paso 3
        run: echo "Simulando paso 3...."

      - name: simulando paso 4
        run: echo "Simulando paso 4...."  

      - name: simulando paso 5
        run: echo "Simulando paso 5...."

      - name: simulando paso 6
        run: echo "Simulando paso 6...."

      - name: simulando paso 7
        run: echo "Simulando paso 7...."

      - name: simulando paso 8
        run: echo "Simulando paso 8...."

      - name: simulando paso 9
        run: echo "Simulando paso 9...."

      - name: simulando paso 10
        run: echo "Simulando paso 10...."
      
      - name: sleep 60 secs
        run: sleep 60