name: workflow reutilizable

on:
  workflow_call:


jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run install
        run: npm install
      
      - name: run build
        run: npm run build